server:
  servlet:
    # UTF-8
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            # 允许跨域的源(网站域名/ip)，设置*为全部
            allowedOrigins: "*"
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            allowedMethods: "*"
            # 允许跨域请求里的head字段，设置*为全部
            allowedHeaders: "*"
      routes:
        - id: tik-user
          uri: lb://tik-user
          predicates:
            - Path=/api/v1/user/**
        - id: tik-hot
          uri: lb://tik-hot
          predicates:
            - Path=/api/v1/hot/**
        - id: tik-comment
          uri: lb://tik-comment
          predicates:
            - Path=/api/v1/comment/**
        - id: tik-video
          uri: lb://tik-video
          predicates:
            - Path=/api/v1/video/**
        - id: tik-picture
          uri: lb://tik-picture
          predicates:
            - Path=/api/v1/picture/**
  data:
    redis:
      port: 6379
      host: 127.0.0.1
      database: 1
      password: 123456