server:
  port: 8004

spring:
  application:
    name: tik-comment
  config:
    import:
      - optional:configserver:${CONFIGSERVER_URL:http://localhost:8888}
  cloud:
    config:
      uri: localhost:8888
      name: tik-comment
      profile: dev
    zookeeper:
      connect-string: localhost:2181

