server:
  port: 8888

spring:
  application:
    name: tik-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/**
          default-label: master
          username:
          password:
